<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Signals.Aspects.DI" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\10 Core\02 Contracts\App.Core.Contracts\App.Core.Contracts.csproj" />
  </ItemGroup>

</Project>
